### ISSUE TITLE
UserAffinities doesn't seem to work ?

### ISSUE THREAD

**Issue by SpoogLord** [ItMeSarah/BD-Addons#2]
Enabled the data personalization setting, installed the plugin, enabled it, can't see affinities.
Restarted Discord, can't see affinities.
Made sure the plugin was still enabled, can't see affinities.
Disabled all other plugins and themes, can't see affinities.

In the BetterDiscord page you say 
> If you did not have the setting enabled and had to accept enabling it through the alert, you will need to wait 24 hours until the UserAffinities store populates and fetches

I did not enable it through the plugin, but I only enabled it minutes before installing the plugin, is that why it hasn't shown up? If that is why, why does the plugin description not say that? 

I will leave it enabled for a day or two and report back if it starts working.

**Comment by SpoogLord** [comment]
It took a few days but now the affinities are showing, but, they're just wrong. Friends I've talked to for literal years online have a score of like 40- if they have a score at all- and relatively new friends have a score of around 15, I don't know if its weighted or a percentage or something but I don't know how to interpret these numbers other than "they're not accurate"

**Comment by ItMeSarah** [comment]
> It took a few days but now the affinities are showing, but, they're just wrong. Friends I've talked to for literal years online have a score of like 40- if they have a score at all- and relatively new friends have a score of around 15, I don't know if its weighted or a percentage or something but I don't know how to interpret these numbers other than "they're not accurate"

If you did not have the setting enabled until just before or after enabling the plugin, it will not have much data to go off of, it populates and calculates after enabling that setting. It's also not a direct 1 to 1 calculation; we also do not know how it is calculated as it's server side relying on that setting.
