### ISSUE TITLE
Is it normal for affinity not to appear for some users?

### ISSUE THREAD

**Issue by GeneralSniper** [ItMeSarah/BD-Addons#3]
For some users that I see the profile, the Affinity Score does not appear, both for friends and non-friends

**Comment by ItMeSarah** [comment]
> For some users that I see the profile, the Affinity Score does not appear, both for friends and non-friends

It's normal if you've just enabled the setting to not have an affinity score until 24 hours after enabling it and then talking/interracting a bit
